import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import './style.css';

const app=document.querySelector('#app');
app.innerHTML=`<div class="top"><div class="eyebrow">BigChange • Interactive Learning</div><h1>Digital Camera Atlas</h1><div class="sub">See exactly how a digital camera turns light into a photograph.</div></div>
<div class="parts"><div class="parts-title">CAMERA COMPONENTS</div>${['Lens','Aperture','Shutter','Sensor','Processor','Card'].map(n=>`<button class="part" data-part="${n}">${n==='Card'?'Memory Card':n}</button>`).join('')}<button id="cut">CUTAWAY</button><button id="explode">EXPLODED VIEW</button></div>
<div class="panel"><div class="eyebrow">SELECTED COMPONENT</div><h2 id="partTitle">Camera Overview</h2><p id="partText">Rotate the camera or choose a component to explore it.</p><div class="flow">LIGHT<br>↓<br>LENS → APERTURE → SHUTTER<br>↓<br>SENSOR → PROCESSOR → CARD</div><button class="primary" id="photo">● TAKE PHOTO</button><button id="reset">RESET VIEW</button><div id="status">Loading realistic CC0 camera…</div></div>
<div class="settings"><label>MODE <select id="mode"><option>Manual</option><option>Aperture Priority</option><option>Shutter Priority</option><option>Program</option></select></label><label>APERTURE <select id="fstop"><option>f/1.8</option><option>f/2.8</option><option selected>f/4</option><option>f/5.6</option><option>f/8</option><option>f/11</option></select></label><label>SHUTTER <select id="speed"><option>1/1000</option><option>1/500</option><option selected>1/250</option><option>1/125</option><option>1/60</option><option>1/30</option></select></label><label>ISO <select id="iso"><option>100</option><option selected>400</option><option>800</option><option>1600</option><option>3200</option></select></label></div>`;

const scene=new THREE.Scene();scene.background=new THREE.Color(0x071018);
const camera=new THREE.PerspectiveCamera(40,innerWidth/innerHeight,.1,100);camera.position.set(6,3.5,7);
const renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.outputColorSpace=THREE.SRGBColorSpace;app.prepend(renderer.domElement);
const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.target.set(0,0,0);controls.minDistance=3.8;controls.maxDistance=13;
scene.add(new THREE.HemisphereLight(0xc8e8ff,0x18212b,2.2));const key=new THREE.DirectionalLight(0xffffff,4);key.position.set(5,8,6);scene.add(key);
const atlas=new THREE.Group();scene.add(atlas);let exterior=null,exploded=false,cutaway=false,pulse=0,selected=null;const pick=[],home={};
const info={Lens:'Focuses incoming light toward the sensor. Focal length changes angle of view and perspective.',Aperture:'Controls how much light enters the camera and how much of the scene appears in focus.',Shutter:'Controls how long the sensor receives light. Fast speeds freeze motion; slow speeds create motion blur.',Sensor:'The CMOS sensor converts focused light into electronic image data.',Processor:'The image processor turns raw sensor data into the final digital image.',Card:'The memory card stores the finished photograph.'};
const mat=c=>new THREE.MeshStandardMaterial({color:c,metalness:.55,roughness:.28});
function add(name,g,m,p,r=[0,0,0]){const x=new THREE.Mesh(g,m);x.name=name;x.position.set(...p);x.rotation.set(...r);x.castShadow=true;home[name]=x.position.clone();atlas.add(x);pick.push(x);return x}
const lens=add('Lens',new THREE.CylinderGeometry(.85,.85,.55,64),mat(0x15191d),[0,0,1.45],[Math.PI/2,0,0]);
const glass=new THREE.Mesh(new THREE.CylinderGeometry(.68,.68,.08,64),new THREE.MeshPhysicalMaterial({color:0x69bde8,transparent:true,opacity:.55,transmission:.35}));glass.rotation.x=Math.PI/2;lens.add(glass);
const aperture=add('Aperture',new THREE.TorusGeometry(.48,.08,16,64),mat(0x22262a),[0,0,.82]);for(let i=0;i<8;i++){const b=new THREE.Mesh(new THREE.BoxGeometry(.42,.11,.03),mat(0x30343a));b.position.set(Math.cos(i*Math.PI/4)*.27,Math.sin(i*Math.PI/4)*.27,0);b.rotation.z=i*Math.PI/4+.45;aperture.add(b)}
add('Shutter',new THREE.BoxGeometry(1.2,.92,.06),mat(0x353b42),[0,0,.42]);add('Sensor',new THREE.BoxGeometry(1.1,.75,.07),new THREE.MeshStandardMaterial({color:0x238aa8,emissive:0x052b31}),[0,0,.16]);add('Processor',new THREE.BoxGeometry(.65,.5,.12),mat(0x17604a),[.9,-.5,-.08]);add('Card',new THREE.BoxGeometry(.36,.58,.09),mat(0x24292e),[1.3,-.4,-.06]);
const beamMat=new THREE.MeshBasicMaterial({color:0x66ddff,transparent:true,opacity:0});const beam=new THREE.Mesh(new THREE.CylinderGeometry(.035,.035,4.4,12),beamMat);beam.rotation.x=Math.PI/2;beam.position.z=2.05;atlas.add(beam);
const floor=new THREE.Mesh(new THREE.CircleGeometry(8,64),new THREE.MeshStandardMaterial({color:0x101a25,roughness:.9}));floor.rotation.x=-Math.PI/2;floor.position.y=-1.55;scene.add(floor);
const MODEL='https://cdn.jsdelivr.net/gh/KhronosGroup/glTF-Sample-Assets@main/Models/AntiqueCamera/glTF-Binary/AntiqueCamera.glb';
new GLTFLoader().load(MODEL,g=>{exterior=g.scene;atlas.add(exterior);const box=new THREE.Box3().setFromObject(exterior),size=box.getSize(new THREE.Vector3()),center=box.getCenter(new THREE.Vector3());exterior.position.sub(center);exterior.scale.setScalar(3.8/Math.max(size.x,size.y,size.z));exterior.rotation.y=Math.PI;exterior.traverse(o=>{if(o.isMesh){o.material=o.material.clone();o.castShadow=true}});status.textContent='Camera ready — choose a component or press Take Photo.'},undefined,()=>status.textContent='Camera model failed to load — check internet.');
const title=document.querySelector('#partTitle'),text=document.querySelector('#partText'),status=document.querySelector('#status');
function select(o){if(!o||!info[o.name])return;if(selected?.material?.emissive)selected.material.emissive.setHex(selected.userData.oldEm||0);selected=o;if(o.material.emissive){o.userData.oldEm=o.material.emissive.getHex();o.material.emissive.setHex(0x145d78)}title.textContent=o.name==='Card'?'Memory Card':o.name;text.textContent=info[o.name];status.textContent='Selected: '+title.textContent;document.querySelectorAll('.part').forEach(b=>b.classList.toggle('active',b.dataset.part===o.name))}
document.querySelectorAll('.part').forEach(b=>b.onclick=()=>select(pick.find(x=>x.name===b.dataset.part)));
const ray=new THREE.Raycaster(),pointer=new THREE.Vector2();renderer.domElement.addEventListener('pointerdown',e=>{pointer.x=e.clientX/innerWidth*2-1;pointer.y=-(e.clientY/innerHeight)*2+1;ray.setFromCamera(pointer,camera);const h=ray.intersectObjects(pick,true)[0];if(h){let o=h.object;while(o.parent&&o.parent!==atlas)o=o.parent;select(o)}});
function shell(){if(!exterior)return;exterior.traverse(o=>{if(o.isMesh){o.material.transparent=cutaway||exploded;o.material.opacity=cutaway||exploded?.12:1;o.material.depthWrite=!(cutaway||exploded)}})}
function explode(on){exploded=on;const z={Lens:3,Aperture:1.65,Shutter:.92,Sensor:.16,Processor:-.85,Card:-1.25};pick.forEach(o=>on?o.position.set(home[o.name].x,home[o.name].y,z[o.name]):o.position.copy(home[o.name]));shell();document.querySelector('#explode').classList.toggle('active',on);status.textContent=on?'Exploded view — follow the light path through each component.':'Camera reassembled.'}
document.querySelector('#explode').onclick=()=>explode(!exploded);document.querySelector('#cut').onclick=()=>{cutaway=!cutaway;shell();document.querySelector('#cut').classList.toggle('active',cutaway);status.textContent=cutaway?'Cutaway enabled — internal components are visible.':'Exterior restored.'};
document.querySelector('#reset').onclick=()=>{cutaway=false;explode(false);camera.position.set(6,3.5,7);controls.target.set(0,0,0);document.querySelector('#cut').classList.remove('active');status.textContent='View reset.'};
document.querySelector('#photo').onclick=()=>{cutaway=true;shell();document.querySelector('#cut').classList.add('active');pulse=3;status.textContent=`${mode.value} • ${fstop.value} • ${speed.value} • ISO ${iso.value} — Light → Lens → Aperture → Shutter → Sensor → Processor → Card`};
const mode=document.querySelector('#mode'),fstop=document.querySelector('#fstop'),speed=document.querySelector('#speed'),iso=document.querySelector('#iso');
const clock=new THREE.Clock();function animate(){requestAnimationFrame(animate);const dt=clock.getDelta();if(pulse>0){pulse-=dt;beamMat.opacity=Math.max(0,.9*Math.sin(Math.max(0,pulse)*7)**2);pick.find(x=>x.name==='Sensor').material.emissiveIntensity=1+Math.max(0,pulse)*1.2}else pick.find(x=>x.name==='Sensor').material.emissiveIntensity=1;controls.update();renderer.render(scene,camera)}animate();
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});