import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import './style.css';
const app=document.querySelector('#app');
app.innerHTML=`<div class="top"><div class="eyebrow">BigChange • Interactive Learning</div><h1>Digital Camera Atlas V2</h1><div class="sub">Real camera exterior • interactive cutaway</div></div><div class="panel"><h2 id="partTitle">Camera Overview</h2><p id="partText">Drag to rotate, scroll to zoom, and select a component.</p><div class="grid"><button id="cut">Cutaway</button><button id="explode">Explode</button><button id="reset">Reset</button><button class="primary" id="photo">Take Photo</button></div><div id="status">Loading CC0 camera…</div></div><div class="legend"><span class="chip">Lens</span><span class="chip">Aperture</span><span class="chip">Shutter</span><span class="chip">Sensor</span><span class="chip">Processor</span><span class="chip">Memory Card</span></div>`;
const scene=new THREE.Scene();scene.background=new THREE.Color(0x071018);const camera=new THREE.PerspectiveCamera(40,innerWidth/innerHeight,.1,100);camera.position.set(6,3.5,7);const renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;document.querySelector('#app').prepend(renderer.domElement);const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.target.set(0,0,0);scene.add(new THREE.HemisphereLight(0xc8e8ff,0x18212b,2.2));const key=new THREE.DirectionalLight(0xffffff,4);key.position.set(5,8,6);scene.add(key);
const atlas=new THREE.Group();scene.add(atlas);let exterior=null,exploded=false,cutaway=false,pulse=0;const pick=[],home={};const info={Lens:'Focuses incoming light toward the sensor.',Aperture:'Controls how much light enters and depth of field.',Shutter:'Controls how long the sensor is exposed.',Sensor:'Converts focused light into electronic image data.',Processor:'Processes sensor data into the final image.',Card:'Stores the finished digital photograph.'};const mat=(c)=>new THREE.MeshStandardMaterial({color:c,metalness:.55,roughness:.28});function add(name,g,m,p,r=[0,0,0]){const x=new THREE.Mesh(g,m);x.name=name;x.position.set(...p);x.rotation.set(...r);x.castShadow=true;home[name]=x.position.clone();atlas.add(x);pick.push(x);return x}
const lens=add('Lens',new THREE.CylinderGeometry(.85,.85,.55,64),mat(0x15191d),[0,0,1.45],[Math.PI/2,0,0]);const glass=new THREE.Mesh(new THREE.CylinderGeometry(.68,.68,.08,64),new THREE.MeshPhysicalMaterial({color:0x69bde8,transparent:true,opacity:.55,transmission:.35}));glass.rotation.x=Math.PI/2;lens.add(glass);const aperture=add('Aperture',new THREE.TorusGeometry(.48,.08,16,64),mat(0x22262a),[0,0,.82]);for(let i=0;i<8;i++){const b=new THREE.Mesh(new THREE.BoxGeometry(.42,.11,.03),mat(0x30343a));b.position.set(Math.cos(i*Math.PI/4)*.27,Math.sin(i*Math.PI/4)*.27,0);b.rotation.z=i*Math.PI/4+.45;aperture.add(b)}add('Shutter',new THREE.BoxGeometry(1.2,.92,.06),mat(0x353b42),[0,0,.42]);add('Sensor',new THREE.BoxGeometry(1.1,.75,.07),new THREE.MeshStandardMaterial({color:0x238aa8,emissive:0x052b31}),[0,0,.16]);add('Processor',new THREE.BoxGeometry(.65,.5,.12),mat(0x17604a),[.9,-.5,-.08]);add('Card',new THREE.BoxGeometry(.36,.58,.09),mat(0x24292e),[1.3,-.4,-.06]);
const beamMat=new THREE.MeshBasicMaterial({color:0x66ddff,transparent:true,opacity:0});const beam=new THREE.Mesh(new THREE.CylinderGeometry(.035,.035,3.5,12),beamMat);beam.rotation.x=Math.PI/2;beam.position.z=1.7;atlas.add(beam);const floor=new THREE.Mesh(new THREE.CircleGeometry(8,64),new THREE.MeshStandardMaterial({color:0x101a25,roughness:.9}));floor.rotation.x=-Math.PI/2;floor.position.y=-1.55;scene.add(floor);
const MODEL='https://cdn.jsdelivr.net/gh/KhronosGroup/glTF-Sample-Assets@main/Models/AntiqueCamera/glTF-Binary/AntiqueCamera.glb';new GLTFLoader().load(MODEL,g=>{exterior=g.scene;atlas.add(exterior);const box=new THREE.Box3().setFromObject(exterior),size=box.getSize(new THREE.Vector3()),center=box.getCenter(new THREE.Vector3());exterior.position.sub(center);exterior.scale.setScalar(3.8/Math.max(size.x,size.y,size.z));exterior.rotation.y=Math.PI;exterior.traverse(o=>{if(o.isMesh)o.material=o.material.clone()});status.textContent='Real CC0 camera loaded — try Cutaway.'},undefined,()=>status.textContent='Camera download failed — check internet.');
const title=document.querySelector('#partTitle'),text=document.querySelector('#partText'),status=document.querySelector('#status');function select(o){if(!o||!info[o.name])return;title.textContent=o.name==='Card'?'Memory Card':o.name;text.textContent=info[o.name];status.textContent='Selected: '+title.textContent}const ray=new THREE.Raycaster(),pointer=new THREE.Vector2();renderer.domElement.addEventListener('pointerdown',e=>{pointer.x=e.clientX/innerWidth*2-1;pointer.y=-(e.clientY/innerHeight)*2+1;ray.setFromCamera(pointer,camera);const h=ray.intersectObjects(pick,true)[0];if(h){let o=h.object;while(o.parent&&o.parent!==atlas)o=o.parent;select(o)}});
function shell(){if(!exterior)return;exterior.traverse(o=>{if(o.isMesh){o.material.transparent=cutaway||exploded;o.material.opacity=cutaway||exploded?.15:1;o.material.depthWrite=!(cutaway||exploded)}})}function explode(on){exploded=on;const z={Lens:3,Aperture:1.55,Shutter:.8,Sensor:.16,Processor:-.8,Card:-1.2};pick.forEach(o=>on?o.position.set(home[o.name].x,home[o.name].y,z[o.name]):o.position.copy(home[o.name]));shell();status.textContent=on?'Exploded view — select a component.':'Camera reassembled.'}document.querySelector('#explode').onclick=()=>explode(!exploded);document.querySelector('#cut').onclick=()=>{cutaway=!cutaway;shell();status.textContent=cutaway?'Cutaway enabled.':'Exterior restored.'};document.querySelector('#reset').onclick=()=>{cutaway=false;explode(false);camera.position.set(6,3.5,7);controls.target.set(0,0,0)};document.querySelector('#photo').onclick=()=>{cutaway=true;shell();pulse=2.2;status.textContent='Light → Lens → Aperture → Shutter → Sensor → Processor → Card'};
const clock=new THREE.Clock();function animate(){requestAnimationFrame(animate);const dt=clock.getDelta();if(pulse>0){pulse-=dt;beamMat.opacity=Math.max(0,.8*pulse/2.2);pick.find(x=>x.name==='Sensor').material.emissiveIntensity=2*pulse/2.2}controls.update();renderer.render(scene,camera)}animate();addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});
